import { useRouter } from "next/router";
import Footer from "./footer";
import Header from "./header";
import { Container, Grid } from "@mui/material";
import DashBoardHeader from "./DashboardHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NO_LAYOUTPATH = ["/signin", "/signup"];
const DASHBOARD_LAYOUTPATH = ["/dashboard", "/quiz", "/lesson", "/tracker"];
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  console.log("router", router.pathname);
  if (NO_LAYOUTPATH.includes(router.pathname)) {
    return <>{children};</>;
  }
  if (
    DASHBOARD_LAYOUTPATH.includes(router.pathname) ||
    router.pathname.includes("/tracker")
  ) {
    return (
      <>
        <DashBoardHeader />
        <Grid
          container
          style={{ marginLeft: 400, width: "calc(100vw - 400px)" }}
        >
          {children}
        </Grid>
      </>
    );
  }
  return (
    <>
      <Header />
      <Container>{children}</Container>
      <Footer />
    </>
  );
}
